name: Build coho page
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build coho.jar
        run: |
          git clone https://github.com/sockeye-d/coho.git /tmp/coho
          cd /tmp/coho
          ./gradlew :cli:shadowJar
          cp cli/build/libs/cli-all.jar ${{ github.workspace }}/cli-all.jar
      - run: java -jar cli-all.jar
      - name: Deploy with Vercel
        uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required'
          vercel-args: --prod
          github-comment: false
          working-directory: build
